[package]
name = "wire-echo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wire-echo"
path = "src/main.rs"

[[bin]]
name = "wire-httpget"
path = "src/bin/httpget.rs"

[[bin]]
name = "wire-perf"
path = "src/bin/perf.rs"

[[bin]]
name = "wire-curl"
path = "src/bin/curl.rs"

[[bin]]
name = "wire-xdp-echo"
path = "src/bin/xdp_echo.rs"

[dependencies]
wire-core = { path = "../wire-core" }
wire-tap = { path = "../wire-tap" }
wire-xdp = { path = "../wire-xdp" }
wire-sim = { path = "../wire-sim" }
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
libc.workspace = true
rustls.workspace = true
